services:
  sub-domain-app:
    healthcheck:
      test: 'curl --fail 127.0.0.1:8000'
    depends_on:
      sub-domain-phpfpm:
        condition: service_started

  sub-domain-phpfpm:
    depends_on:
      sub-domain-db:
        condition: service_healthy
      sub-domain-redis:
        condition: service_healthy
      sub-domain-opensearch:
        condition: service_healthy
      sub-domain-rabbitmq:
        condition: service_healthy
      # elasticsearch:
      #  condition: service_healthy

  sub-domain-db:
    healthcheck:
      test: 'mysqladmin ping -h localhost -u root -pmagento'
      interval: 5s
      timeout: 5s
      retries: 30

  sub-domain-redis:
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 5s
      timeout: 5s
      retries: 30

  sub-domain-opensearch:
    healthcheck:
      test: 'curl --fail opensearch:9200/_cat/health >/dev/null || exit 1'
      interval: 5s
      timeout: 5s
      retries: 30

  # elasticsearch:
  #  healthcheck:
  #    test: 'curl --fail elasticsearch:9200/_cat/health >/dev/null || exit 1'
  #    interval: 5s
  #    timeout: 5s
  #    retries: 30

  sub-domain-rabbitmq:
    healthcheck:
      test: 'rabbitmq-diagnostics -q ping'
      interval: 5s
      timeout: 5s
      retries: 30

  # mailcatcher:
  #   healthcheck:
  #     test: 'wget --no-verbose --tries=1 --spider 127.0.0.1:1080 || exit 1'
